### ISSUE TITLE
コメント内コメントの前処理結果でコメントが残る

### ISSUE THREAD

**Issue by hoshiimo28** [ytgw/CodeCommentTranslator#1]
### 実行言語
C++

### 処理前文字列
//{ 29,	""},	/* Sami*/

### 出力結果
{ 29,	""},	/* Sami

### 期待出力
{ 29,	""},	/* Sami*/
or
{ 29,	""},	Sami

**Comment by ytgw** [comment]
Issueの投稿ありがとうございます。
「//{ 29, ""}, /* Sami*/」に対して「{ 29, ""}, /* Sami*/」が出力されるように修正しました。
